"""baseline_schema

Revision ID: d3f684a46f96
Revises: 
Create Date: 2026-07-02 16:02:37.458870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3f684a46f96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suppliers')
    op.alter_column('action_status_log', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('action_status_log', 'changed_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_action_status_log_action'), table_name='action_status_log')
    op.create_index(op.f('ix_action_status_log_action_id'), 'action_status_log', ['action_id'], unique=False)
    op.alter_column('actions', 'plan_status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('ix_cn_response_token'), table_name='claim_notifications')
    op.create_index(op.f('ix_claim_notifications_response_token'), 'claim_notifications', ['response_token'], unique=False)
    op.alter_column('documents', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('documents', 'upload_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('idx_npi_profiles_excluded'), table_name='npi_profiles')
    op.drop_index(op.f('idx_npi_profiles_state'), table_name='npi_profiles')
    op.alter_column('npi_risk_scores', 'identity_reuse_flag',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('npi_risk_scores', 'hospice_duration_flag',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('npi_risk_scores', 'upcoding_flag',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('npi_risk_scores', 'unbundling_flag',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('physicians', 'first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('physicians', 'last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('physicians', 'taxonomy_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('physicians', 'email_primary',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('physicians', 'notification_mode',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('physicians', 'auto_escalate_hours',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('physicians', 'verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('physicians', 'practice_city')
    op.drop_column('physicians', 'organization_name')
    op.drop_column('physicians', 'primary_taxonomy_switch')
    op.drop_column('physicians', 'middle_name')
    op.drop_column('physicians', 'credential_text')
    op.drop_column('physicians', 'entity_type_code')
    op.drop_column('physicians', 'practice_postal_code')
    op.drop_column('physicians', 'last_update_date')
    op.drop_column('physicians', 'sex_code')
    op.drop_column('physicians', 'practice_state')
    op.drop_column('physicians', 'deactivation_date')
    op.drop_column('physicians', 'enumeration_date')
    op.drop_column('physicians', 'oig_excluded')
    op.alter_column('supplier_profiles', 'state',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('supplier_profiles', 'zip',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('supplier_profiles', 'npi_watch_registered',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('supplier_profiles', 'is_synthetic',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_supplier_excluded'), table_name='supplier_profiles')
    op.drop_index(op.f('idx_supplier_state'), table_name='supplier_profiles')
    op.alter_column('users', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'needs_manual_review',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'organization_name',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'organization_name',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text('NULL::character varying'),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'needs_manual_review',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('idx_supplier_state'), 'supplier_profiles', ['state'], unique=False)
    op.create_index(op.f('idx_supplier_excluded'), 'supplier_profiles', ['oig_excluded'], unique=False)
    op.alter_column('supplier_profiles', 'is_synthetic',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('supplier_profiles', 'npi_watch_registered',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('supplier_profiles', 'zip',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('supplier_profiles', 'state',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.add_column('physicians', sa.Column('oig_excluded', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('physicians', sa.Column('enumeration_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('physicians', sa.Column('deactivation_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('physicians', sa.Column('practice_state', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('physicians', sa.Column('sex_code', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.add_column('physicians', sa.Column('last_update_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('physicians', sa.Column('practice_postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('physicians', sa.Column('entity_type_code', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('physicians', sa.Column('credential_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('physicians', sa.Column('middle_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('physicians', sa.Column('primary_taxonomy_switch', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.add_column('physicians', sa.Column('organization_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('physicians', sa.Column('practice_city', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('physicians', 'verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('physicians', 'auto_escalate_hours',
               existing_type=sa.INTEGER(),
               server_default=sa.text('72'),
               existing_nullable=False)
    op.alter_column('physicians', 'notification_mode',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'REALTIME'::character varying"),
               existing_nullable=False)
    op.alter_column('physicians', 'email_primary',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('physicians', 'taxonomy_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('physicians', 'last_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('physicians', 'first_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('npi_risk_scores', 'unbundling_flag',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('npi_risk_scores', 'upcoding_flag',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('npi_risk_scores', 'hospice_duration_flag',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('npi_risk_scores', 'identity_reuse_flag',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_index(op.f('idx_npi_profiles_state'), 'npi_profiles', ['practice_state'], unique=False)
    op.create_index(op.f('idx_npi_profiles_excluded'), 'npi_profiles', ['oig_excluded'], unique=False)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('documents', 'upload_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending_review'::character varying"),
               existing_nullable=True)
    op.alter_column('documents', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_claim_notifications_response_token'), table_name='claim_notifications')
    op.create_index(op.f('ix_cn_response_token'), 'claim_notifications', ['response_token'], unique=False)
    op.alter_column('actions', 'plan_status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'pending'::character varying"),
               nullable=True)
    op.drop_index(op.f('ix_action_status_log_action_id'), table_name='action_status_log')
    op.create_index(op.f('idx_action_status_log_action'), 'action_status_log', ['action_id'], unique=False)
    op.alter_column('action_status_log', 'changed_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('action_status_log', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table('suppliers',
    sa.Column('npi', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('entity_type_code', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('organization_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('middle_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('credential_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('practice_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('practice_city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('practice_state', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('practice_postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('enumeration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('last_update_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('deactivation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('sex_code', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('taxonomy_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('primary_taxonomy_switch', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('oig_excluded', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('npi', name=op.f('suppliers_pkey'))
    )
    # ### end Alembic commands ###
